######################################################################
##
## Filename: vending_machine_test.udo
## Created on: Thu Apr 25 13:46:03 Rom, sommertid 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
